### PR TITLE
CryptoYa: Exclude Binance

### PR DESCRIPTION
**Pull request by alvasw**
Our Binance price provider gets the exchange rate from Binance already.

Based on #30.

### CODE REVIEW

**Comment by ghost** [comment]
Binance is providing an ARS blue rate (since 2023-06-20 apparently).  Then it is getting transformed to approx 2x by the BlueRateTransformer.  Is the solution enough to mark Binance as `implements BlueRateProvider` ?


    INFO  b.p.s.p.Binance: BTC/ARS: 1.9447208E7
    INFO  b.p.s.ExchangeRateService: ARS transformed from 1.9447208E7 to 3.8947405667574935E7



image

**Comment by ghost** [comment]
If the provider is a BlueRateProvider, can we return `Optional.empty()` instead of the source rate in order to not get the log entries about transforming a rate which is not transformed?

https://github.com/bisq-network/bisq-pricenode/blob/94b26749afd1d6f70823f11ea6118dd03c4bfb2f/src/main/java/bisq/price/spot/ArsBlueRateTransformer.java#L36-L38

    Sep-13 16:12:38.595 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateController: Incoming /getAllMarketPrices request from: curl/7.74.0 
    Sep-13 16:12:38.606 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.9385829E7 to 1.9385829E7 
    Sep-13 16:12:38.607 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.977498364E7 to 1.977498364E7 
    Sep-13 16:12:38.607 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.91121221E7 to 1.91121221E7 
    Sep-13 16:12:38.612 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 3.448917347E7 to 3.448917347E7 
    Sep-13 16:12:38.614 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.924531346E7 to 1.924531346E7 
    Sep-13 16:12:38.615 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.948487433E7 to 1.948487433E7 
    Sep-13 16:12:38.615 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.935150975E7 to 1.935150975E7 
    Sep-13 16:12:38.616 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.945385919E7 to 1.945385919E7 
    Sep-13 16:12:38.616 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.9574875E7 to 1.9574875E7 
    Sep-13 16:12:38.616 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.981790931E7 to 1.981790931E7 
    Sep-13 16:12:38.616 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.986981407E7 to 1.986981407E7 
    Sep-13 16:12:38.618 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.949855053E7 to 1.949855053E7 
    Sep-13 16:12:38.618 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.979064466E7 to 1.979064466E7 
    Sep-13 16:12:38.619 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.939909099E7 to 1.939909099E7 
    Sep-13 16:12:38.619 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.938285981E7 to 1.938285981E7 
    Sep-13 16:12:38.620 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.981663887E7 to 1.981663887E7 
    Sep-13 16:12:38.620 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.95194E7 to 1.95194E7 
    Sep-13 16:12:38.620 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.914822415E7 to 1.914822415E7 
    Sep-13 16:12:38.621 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.9444018E7 to 1.9444018E7 
    Sep-13 16:12:38.621 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 1.973578779E7 to 1.973578779E7 
    Sep-13 16:12:38.632 [http-nio-8080-exec-1] INFO  b.p.s.ExchangeRateService: ARS transformed from 9176884.39 to 1.837877391457766E7

**Comment by ghost** [comment]
I tested :+1: with the 2 suggested changes above.  Would be good to get them included @alvasw.

**Comment by alvasw** [comment]
I created opened a new PR (#32) in which I mark Binance as `BlueRateProvider` and only log the transformed exchange rates.

**Review by ghost — APPROVED** [review]
ACK

**Review by gabernard — APPROVED** [review]
utACK based on https://github.com/bisq-network/bisq-pricenode/pull/31#pullrequestreview-1630098321.

**Pull request merged**
