### PR TITLE
Fix tests. QuoineTest removed.

### PR DESCRIPTION
**Pull request by ghost**
A recent change broke the tests.
The Quoine provider has been obsoleted, test removed.

### CODE REVIEW

**Comment by ghost** [comment]
@Emzy, in the production pricenode, Binance API is down / provider is dead.  The Binance test fails for the same reason.  Do we want to remove the Binance provider?

**Comment by Emzy** [comment]
> @Emzy, in the production pricenode, Binance API is down / provider is dead. The Binance test fails for the same reason. Do we want to remove the Binance provider?

It's a major exchange and AFAIK has fiat on/off-ramps. I think it would be very good to have a price feed from there.
Could it be that the API changed?

**Comment by jmacxx** [comment]
Seems the Binance error was HTTP status 451 (their API is geoblocking).  So not an issue as long as the current pricenodes are ok with it.  Just means you can't really run a pricenode within a country that censors Binance.

**Comment by Emzy** [comment]
Looks like Binance works on my pricenode. So, it's not a problem in the code.

**Comment by ghost** [comment]
My mistake, was not running the pricenode correctly.  This PR is ready for review / merge.

**Comment by Emzy** [comment]
Tested ACK
No errors at the tests and it's running fine on my pricenode.

**Comment by rodvar** [comment]
Probably be good to merge this one before my PR (https://github.com/bisq-network/bisq-pricenode/pull/15) and I can rebase it and remove the temporary fixes that I've used to be able to keep going

**Comment by alvasw** [comment]
@alejandrogarcia83 @gabernard  We need this PR to build the pricenode. Please merge this PR!

**Review by gabernard — APPROVED** [review]
utACK

**Pull request merged**
